# Site settings
title: "The Silent Podcast"
summary: "10 minutes of stillness in your day."
description: "The Silent Podcast is a 10-minute pocket of stillness in your day. Listen to it at a set time every day, in the middle of a busy commute, or when you simply need a break from all of the hustle and bustle of distraction around you."
lang: "en-us"
author: "Gabriel Krieshok"
email: "gabriel.krieshok@gmail.com"
copyright: "2024"
baseurl: ""
url: "https://thesilentpodcast.com"

# Permalink
permalink: /:year-:month-:day.html

# Timezone
timezone: America/New_York

future: true

# Build settings
markdown: kramdown

# Exclude local build settings
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'rakefile', 'vendor', 'node_modules']
