name: Trigger Netlify Build Daily

on:
  schedule:
    - cron: '0 6 * * *' # This will run at 6 AM UTC every day
  workflow_dispatch: # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Trigger Netlify Deploy
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      run: |
        curl -X POST -H "Content-Type: application/json" \
        -H "Authorization: Bearer $NETLIFY_AUTH_TOKEN" \
        -d '{}' \
        https://api.netlify.com/build_hooks/6686e6a33503705635e5a0fd
